### ISSUE TITLE
Add a converter from YAML to CLIP pages

### ISSUE THREAD

**Issue by EmilySeville7cfg** [emilyseville7cfg-better-tldr/prototypes#21]
And create JSON schema for YAML files. I think it's a nice addition as it's one of the simplest ways to provide intellisence while writing pages.

They could look like this:

```yaml
command: am
summary:
  description: Android activity manager
  more-information: https://developer.android.com/studio/command-line/adb#am
examples:
  - description: Start a specific activity
    code: "am start -n {string activity: com.android.settings/.Settings}"
  - description: Start an activity and pass [d]ata to it
    code: "am start -a {string activity: android.intent.action.VIEW} -d {string data: tel:123}"
  - description: Start an activity matching a specific action and [c]ategory
    code: "am start -a {string activity: android.intent.action.MAIN} -c {string category: android.intent.category.HOME}"
  - description: Convert an intent to a URI
    code: "am to-uri -a {string activity: android.intent.action.VIEW} -d {string data: tel:123}"
```

or this in TOML:

```toml
command = "am"

[summary]
description = "Android activity manager"
more-information = "https://developer.android.com/studio/command-line/adb#am"

[[examples]]
description = "Start a specific activity"
code = "am start -n {string activity: com.android.settings/.Settings}"

[[examples]]
description = "Start an activity and pass [d]ata to it"
code = "am start -a {string activity: android.intent.action.VIEW} -d {string data: tel:123}"

[[examples]]
description = "Start an activity matching a specific action and [c]ategory"
code = "am start -a {string activity: android.intent.action.MAIN} -c {string category: android.intent.category.HOME}"

[[examples]]
description = "Convert an intent to a URI"
code = "am to-uri -a {string activity: android.intent.action.VIEW} -d {string data: tel:123}"
```
